apiVersion: v1
kind: Pod
metadata:
  name: scalter
  labels:
    app: scalter
spec:
  containers:
  - name: scalter-python
    image: akashrajeshnair/student_project:latest
    ports:
    - containerPort: 5000