apiVersion: v1
kind: Pod
metadata:
  name: nginx-dsc
  labels:
    app: nginx-dsc
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    configMap:
      name: dsc-html